# RabbitMQ settings
RABBITMQ_URL: "rabbitmq"
RABBITMQ_UPLOAD_QUEUE: "new_file_uploaded"

# MongoDB settings
MONGO_URL: "mongodb"
MONGO_USER: "admin"
MONGO_PASSWORD: "password"
MONGO_DB: "tf2tfjs"
MONGO_COLLECTION: "processed"

# API and Consumer settings
FOLDER:
    UPLOAD: "./uploads/"
    TMP: "./tmp/"
    CONVERTED: "./converted/"

# API settings
API_HOST: "0.0.0.0"
API_PORT: 5000
